# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1


commands:
    test_steps_python:
        description: "Python test steps"
        steps:
            - checkout

            - run:
                name: setup venv
                command: |
                    python3 -m venv --copies venv
                    . venv/bin/activate
                    python3 -m pip install -r requirements.txt

            - run:
                name: install geonetworkx
                command: |
                    . venv/bin/activate
                    python3 -m pip install -e .

            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    python -m nose --with-xunit

            - store_artifacts:
                path: nosetests.xml
                destination: nosetests_${PYVERS}.xml

            - store_test_results:
                path: nosetests.xml


jobs:
    python37:
        parallelism: 2
        docker:
            - image: circleci/python:3.7
              environment:
                  PYVERS: 37

        working_directory: ~/repo

        steps:
            - test_steps_python

    python36:
        parallelism: 2
        docker:
            - image: circleci/python:3.6
              environment:
                  PYVERS: 36

workflows:
    version: 2
    run_tests:
        jobs:
            - python37
            - python36
